### PR TITLE
update repo links

### PR DESCRIPTION
**Pull request by spdegabrielle**

### CODE REVIEW

**Comment by spdegabrielle** [comment]
@vishesh this doesn’t seem to have updated http://play.racketscript.org/
The repo links still go to https://github.com/vishesh/racketscript

https://github.com/vishesh/racketscript-playground

**Comment by vishesh** [comment]
Thanks for point out. It appears our "Publish to Docker" workflow is broken. https://github.com/racketscript/racketscript-playground/issues/32

Looking into it. Not sure if I can just build and push image manually in my M1 MacBook.

**Comment by vishesh** [comment]
Meanwhile I can try building on our server directly. @stchang did we ever build docker image there? Just wondering if we maxed out the RAM when we did it last time, or I may be mixing it with something else.

**Comment by vishesh** [comment]
Website is updated. Also applied for Docker Open Source program for free automated builds. Meanwhile, build using GH Actions on my personal repository is working for now.

**Pull request merged**
